- name: Identify High CPU and Memory Consuming Processes & Close Incident in ServiceNow
  hosts: winserverhost
  gather_facts: no

  vars:
    servicenow_instance: "https://dev262979.service-now.com"
    servicenow_username: "LavanyaR"
    servicenow_password: "7@%C$4c{"  # â— Use Ansible Vault for security
    incident_number: "INC0010792"  # Replace with your incident number

  tasks:
    # ðŸ”¹ Step 1: Retrieve sys_id from ServiceNow for the given Incident Number
    - name: Get sys_id of the incident
      uri:
        url: "{{ servicenow_instance }}/api/now/table/incident?sysparm_query=number={{ incident_number }}"
        method: GET
        headers:
          Accept: "application/json"
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        status_code: 200
        return_content: yes
      register: incident_response

    - name: Extract sys_id from response
      set_fact:
        incident_sys_id: "{{ incident_response.json.result[0].sys_id | default('') }}"

    - name: Display sys_id (For Debugging)
      debug:
        msg: "âœ… Retrieved sys_id: {{ incident_sys_id }}"

    # ðŸ”¹ Step 2: Close the Incident using sys_id
    - name: Close Incident in ServiceNow
      uri:
        url: "{{ servicenow_instance }}/api/now/table/incident/{{ incident_sys_id }}"
        method: PATCH
        headers:
          Content-Type: "application/json"
        user: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
        force_basic_auth: yes
        body: 
          state: "Resolved"
          close_notes: "High CPU/memory issue resolved by automation."
        body_format: json
        status_code: 200, 204
      when: incident_sys_id | length > 0
