- name: Check Disk Utilization 
  hosts: winserverhost
  gather_facts: no

  tasks:
    - name: Fetch disk utilization details for C drive
      win_shell: |
        Get-WmiObject Win32_LogicalDisk | Where-Object { $_.DeviceID -eq "C:" } | 
        Select-Object DeviceID, 
                      @{Name="TotalSize_MB"; Expression={[math]::Round($_.Size / 1MB, 2)}}, 
                      @{Name="FreeSpace_MB"; Expression={[math]::Round($_.FreeSpace / 1MB, 2)}}, 
                      @{Name="UsedSpace_MB"; Expression={[math]::Round(($_.Size - $_.FreeSpace) / 1MB, 2)}}, 
                      @{Name="FreeSpace_Percentage"; Expression={[math]::Round(($_.FreeSpace / $_.Size) * 100, 2)}} | 
        Format-Table -AutoSize | Out-String
      register: c_drive_usage

    - name: Fetch disk utilization details for D drive
      win_shell: |
        if (Get-WmiObject Win32_LogicalDisk | Where-Object { $_.DeviceID -eq "D:" }) {
          Get-WmiObject Win32_LogicalDisk | Where-Object { $_.DeviceID -eq "D:" } | 
          Select-Object DeviceID, 
                        @{Name="TotalSize_MB"; Expression={[math]::Round($_.Size / 1MB, 2)}}, 
                        @{Name="FreeSpace_MB"; Expression={[math]::Round($_.FreeSpace / 1MB, 2)}}, 
                        @{Name="UsedSpace_MB"; Expression={[math]::Round(($_.Size - $_.FreeSpace) / 1MB, 2)}}, 
                        @{Name="FreeSpace_Percentage"; Expression={[math]::Round(($_.FreeSpace / $_.Size) * 100, 2)}} | 
          Format-Table -AutoSize | Out-String
        } else {
          Write-Output "D: drive not found"
        }
      register: d_drive_usage

    - name: Display disk utilization for C drive
      debug:
        msg: "{{ c_drive_usage.stdout_lines }}"

    - name: Display disk utilization for D drive
      debug:
        msg: "{{ d_drive_usage.stdout_lines }}"
