- name: Check Disk Utilization 
  hosts: winserverhost
  gather_facts: no

  tasks:
    - name: Fetch disk utilization details for all drives
      win_shell: |
        Get-WmiObject Win32_LogicalDisk | ForEach-Object { 
          [PSCustomObject]@{
            DeviceID = $_.DeviceID
            TotalSize_MB = [math]::Round($_.Size / 1MB, 2)
            FreeSpace_MB = [math]::Round($_.FreeSpace / 1MB, 2)
            UsedSpace_MB = [math]::Round(($_.Size - $_.FreeSpace) / 1MB, 2)
            FreeSpace_Percentage = [math]::Round(($_.FreeSpace / $_.Size) * 100, 2)
          }
        } | Format-Table -AutoSize | Out-String
      register: disk_usage

    - name: Display disk utilization for all drives
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
