- name: Check Disk Utilization 
  hosts: winserverhost
  gather_facts: no

  tasks:
    - name: Fetch disk utilization details for C and D drives
      win_shell: |
        Get-WmiObject Win32_LogicalDisk | Where-Object { $_.DeviceID -in @("C:", "D:") } | 
        Select-Object DeviceID, 
                      @{Name="TotalSize_MB"; Expression={[math]::Round($_.Size / 1MB, 2)}}, 
                      @{Name="FreeSpace_MB"; Expression={[math]::Round($_.FreeSpace / 1MB, 2)}}, 
                      @{Name="UsedSpace_MB"; Expression={[math]::Round(($_.Size - $_.FreeSpace) / 1MB, 2)}}, 
                      @{Name="FreeSpace_Percentage"; Expression={[math]::Round(($_.FreeSpace / $_.Size) * 100, 2)}} | 
        Format-Table -AutoSize | Out-String
      register: disk_usage

    - name: Display disk utilization for C and D drives
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
