- name: Kill a Specific Process After Confirmation
  hosts: winserverhost
  gather_facts: no

  tasks:
    - name: Validate Input
      fail:
        msg: "❌ Process ID is required. Please provide a valid process ID."
      when: process_id is not defined or process_id | int <= 0

    - name: Kill the process if user confirms
      win_shell: |
        if ("{{ confirm_kill | lower }}" -eq "yes") {
          taskkill /F /PID {{ process_id }}
          Write-Output "❌ Process with PID {{ process_id }} has been forcefully killed."
        } else {
          Write-Output "✅ Process termination cancelled."
        }
      register: kill_process_output
      when: confirm_kill | lower == "yes"

    - name: Display process kill result
      debug:
        msg: "{{ kill_process_output.stdout_lines | default('Operation cancelled by user.') }}"
