- name: Office Printer Automation
  hosts: windows_host
  gather_facts: no

  vars:
    printer_name: "OfficePrinter1"  # Update as per your printer's name
    printer_ip: "192.168.1.100"     # Set this IP statically to avoid manual prompts

  tasks:

    # 1️⃣ Check Wi-Fi Connection
    - name: Get Wi-Fi Connection Details
      win_shell: |
        (Get-NetAdapter -InterfaceDescription "*Wireless*").InterfaceAlias
      register: wifi_status
      ignore_errors: yes

    - name: Debug - Show Wi-Fi Connection
      debug:
        msg: "🔍 Connected to Wi-Fi: {{ wifi_status.stdout }}"
      when: wifi_status.stdout | length > 0

    # 2️⃣ Check if Printer IP is Configured
    - name: Get Existing Printer Ports
      win_shell: |
        Get-PrinterPort | Select-Object -ExpandProperty Name
      register: printer_ports

    - name: Debug - Printer IP Check
      debug:
        msg: "✅ Printer IP {{ printer_ip }} is configured."
      when: printer_ip in printer_ports.stdout_lines

    # 3️⃣ Install or Reinstall Printer Drivers
    - name: List Installed Printer Drivers
      win_shell: |
        pnputil /enum-drivers
      register: installed_drivers

    - name: Debug - Installed Drivers
      debug:
        msg: "{{ installed_drivers.stdout_lines }}"

    - name: Reinstall Printer Drivers (Optional Cleanup)
      win_shell: |
        Get-PrinterDriver | ForEach-Object {
          pnputil /delete-driver $_.Name /force
        }
      register: driver_removal_result
      ignore_errors: yes

    - name: Install Printer Driver
      win_shell: |
        pnputil /add-driver "C:\Path\To\Driver.inf" /install
      register: driver_install_result
      ignore_errors: yes

    - name: Debug - Printer Driver Installation
      debug:
        msg: "📢 Printer drivers installed successfully."

    # 4️⃣ Add Printer with IP and Driver
    - name: Add Printer with IP
      win_shell: |
        Add-Printer -Name "{{ printer_name }}" -PortName "{{ printer_ip }}" -DriverName "{{ installed_drivers.stdout }}"
      register: printer_install_result

    - name: Debug - Printer Added
      debug:
        msg: "🖨️ Printer '{{ printer_name }}' setup complete with IP: {{ printer_ip }}"
      when: printer_install_result is succeeded

    # 5️⃣ Set Default Printer
    - name: Get Default Printer
      win_shell: |
        (Get-Printer | Where-Object { $_.IsDefault -eq $true }).Name
      register: default_printer

    - name: Set as Default Printer (if not already)
      win_shell: |
        (New-Object -ComObject WScript.Network).SetDefaultPrinter("{{ printer_name }}")
      when: printer_name not in default_printer.stdout

    - name: Debug - Set as Default
      debug:
        msg: "✅ '{{ printer_name }}' is now the default printer."

    # 6️⃣ Handle Stuck Print Jobs
    - name: Find Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object {
          Get-PrintJob -PrinterName $_.Name | Where-Object { $_.JobStatus -match "Error" }
        }
      register: stuck_jobs

    - name: Remove Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object {
          Get-PrintJob -PrinterName $_.Name | Where-Object { $_.JobStatus -match "Error" } | ForEach-Object {
            Remove-PrintJob -PrinterName $_.Name -ID $_.ID
          }
        }
      when: stuck_jobs.stdout | length > 0

    - name: Save Stuck Jobs to File
      win_shell: |
        $outputPath = "C:\\Users\\Public\\Documents\\FailedPrintJobs\\StuckJobs.xml"
        $stuckJobs = Get-Printer | ForEach-Object {
          Get-PrintJob -PrinterName $_.Name | Where-Object { $_.JobStatus -match "Error" }
        }
        $stuckJobs | Export-Clixml -Path $outputPath
      when: stuck_jobs.stdout | length > 0

    - name: Debug - Jobs Cleared and Saved
      debug:
        msg: "🚀 Stuck print jobs removed and saved to C:\\Users\\Public\\Documents\\FailedPrintJobs\\StuckJobs.xml"

    # 7️⃣ Ensure Printer is Online
    - name: Get Printer Online Status
      win_shell: |
        (Get-Printer -Name "{{ printer_name }}").PrinterStatus
      register: printer_status

    - name: Restart Spooler if Offline
      win_shell: |
        Restart-Service Spooler
      when: "'Offline' in printer_status.stdout"

    - name: Debug - Printer Online
      debug:
        msg: "✅ Printer '{{ printer_name }}' is online."
      when: "'Offline' not in printer_status.stdout"
