---
- name: Printer Troubleshooting Automation
  hosts: all
  gather_facts: no
  tasks:

    - name: Restart Print Spooler Service
      win_service:
        name: Spooler
        state: restarted
      when: issue_type == "spooler_restart" or issue_type == "all"

    - name: Clear Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object { Remove-PrintJob -PrinterName $_.Name }
      when: issue_type == "stuck_jobs" or issue_type == "all"
      ignore_errors: yes

    - name: Check Printer Connectivity
      win_shell: |
        Test-Connection -ComputerName {{ printer_ip }} -Count 2
      register: ping_result
      when: issue_type == "connectivity" or issue_type == "all"
      ignore_errors: yes

    - name: Show Connectivity Result
      debug:
        msg: "{{ ping_result.stdout_lines }}"
      when: issue_type == "connectivity" or issue_type == "all"

    - name: Fix Printer Showing Offline
      win_shell: |
        Get-Printer | ForEach-Object { Set-Printer -Name $_.Name -Online }
      when: issue_type == "offline_status" or issue_type == "all"

    - name: Set Correct Default Printer
      win_shell: |
        $defaultPrinter = Get-Printer | Where-Object { $_.IsDefault -eq $true }
        if (-not $defaultPrinter) {
          $printerList = Get-Printer
          if ($printerList) {
            Set-Printer -Name ($printerList[0].Name) -Default
          }
        }
      when: issue_type == "offline_status" or issue_type == "all"

    - name: Detect Installed Printer Model
      win_shell: |
        (Get-Printer | Select-Object -ExpandProperty DriverName) -join ', '
      register: installed_printer_driver
      when: issue_type == "driver_update" or issue_type == "all"

    - name: Debug - Show Installed Driver
      debug:
        msg: "Installed Printer Driver: {{ installed_printer_driver.stdout }}"
      when: issue_type == "driver_update" or issue_type == "all"

    - name: Install Missing Printer Driver (from Network Share or Local Repository)
      win_shell: |
        $printerModel = Get-Printer | Select-Object -ExpandProperty DriverName
        if ($printerModel -like "*HP*") {
          $driverPath = "\\fileserver\drivers\hp_driver.exe"
          $localDriverPath = "C:\Drivers\hp_driver.exe"
        } elseif ($printerModel -like "*Canon*") {
          $driverPath = "\\fileserver\drivers\canon_driver.exe"
          $localDriverPath = "C:\Drivers\canon_driver.exe"
        } else {
          $driverPath = "\\fileserver\drivers\generic_driver.exe"
          $localDriverPath = "C:\Drivers\generic_driver.exe"
        }

        if (Test-Path $driverPath) {
          Copy-Item -Path $driverPath -Destination "C:\Temp\printer_driver.exe"
          $driverToInstall = "C:\Temp\printer_driver.exe"
        } elseif (Test-Path $localDriverPath) {
          Copy-Item -Path $localDriverPath -Destination "C:\Temp\printer_driver.exe"
          $driverToInstall = "C:\Temp\printer_driver.exe"
        } else {
          Write-Output "Driver file not found on network share or local repository"
          exit 1
        }

        Start-Process -FilePath $driverToInstall -ArgumentList "/S" -Wait
      when: issue_type == "driver_update" or issue_type == "all"
      ignore_errors: yes
