---
- name: Printer Troubleshooting Automation
  hosts: all
  gather_facts: no
  tasks:

    - name: Restart Print Spooler Service
      win_service:
        name: Spooler
        state: restarted
      when: ansible_host == target_machine and issue_type == "spooler_restart"

    - name: Clear Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object { Remove-PrintJob -PrinterName $_.Name }
      when: ansible_host == target_machine and issue_type == "stuck_jobs"
      ignore_errors: yes

    - name: Check Printer Connectivity
      win_shell: |
        Test-Connection -ComputerName PRINTER_IP -Count 2
      register: ping_result
      when: ansible_host == target_machine and issue_type == "connectivity"

    - name: Show Connectivity Result
      debug:
        msg: "{{ ping_result.stdout_lines }}"
      when: ansible_host == target_machine and issue_type == "connectivity"

    - name: Fix Printer Showing Offline
      win_shell: |
        Get-Printer | ForEach-Object { Set-Printer -Name $_.Name -Online }
      when: ansible_host == target_machine and issue_type == "offline_status"

    - name: Set Correct Default Printer
      win_shell: |
        $defaultPrinter = Get-Printer | Where-Object { $_.IsDefault -eq $true }
        if (-not $defaultPrinter) {
          $printerList = Get-Printer
          if ($printerList) {
            Set-Printer -Name ($printerList[0].Name) -Default
          }
        }
      when: ansible_host == target_machine and issue_type == "offline_status"

    - name: Detect Installed Printer Model
      win_shell: |
        (Get-Printer | Select-Object -ExpandProperty DriverName) -join ', '
      register: installed_printer_driver
      when: ansible_host == target_machine and issue_type == "driver_update"

    - name: Debug - Show Installed Driver
      debug:
        msg: "Installed Printer Driver: {{ installed_printer_driver.stdout }}"
      when: ansible_host == target_machine and issue_type == "driver_update"

    - name: Download Correct Printer Driver (if missing)
      win_shell: |
        $printerModel = Get-Printer | Select-Object -ExpandProperty DriverName
        if ($printerModel -like "*HP*") {
          $driverURL = "http://printer-drivers-server/hp_driver.exe"
        } elseif ($printerModel -like "*Canon*") {
          $driverURL = "http://printer-drivers-server/canon_driver.exe"
        } else {
          $driverURL = "http://printer-drivers-server/generic_driver.exe"
        }

        Invoke-WebRequest -Uri $driverURL -OutFile "C:\Temp\printer_driver.exe"
      args:
        creates: "C:\\Temp\\printer_driver.exe"
      when: ansible_host == target_machine and issue_type == "driver_update"

    - name: Install Correct Printer Driver
      win_shell: |
        Start-Process -FilePath "C:\Temp\printer_driver.exe" -ArgumentList "/S" -Wait
      when: ansible_host == target_machine and issue_type == "driver_update"
      ignore_errors: yes
