---
- name: Printer Troubleshooting
  hosts: "{{ target_machine }}"  # This will be provided at runtime
  gather_facts: no
  tasks:

    - name: Restart Print Spooler Service
      win_service:
        name: Spooler
        state: restarted

    - name: Clear Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object { Remove-PrintJob -PrinterName $_.Name }
      when: issue_type == "stuck_jobs"

    - name: Check Printer Connectivity
      win_shell: |
        Test-Connection -ComputerName PRINTER_IP -Count 2
      register: ping_result
      when: issue_type == "connectivity"

    - name: Show Connectivity Result
      debug:
        msg: "{{ ping_result.stdout_lines }}"
      when: issue_type == "connectivity"

    - name: Install Missing Printer Driver (Example)
      win_package:
        path: "\\fileserver\drivers\printer_driver.exe"
        state: present
      when: issue_type == "driver_update"
