- name: Printer Troubleshooting Automation
  hosts: windows_host
  gather_facts: no

  tasks:
    # 1️⃣ Check Connection to Windows Server
    - name: Check Connection to Windows Server
      win_ping:
      register: connection_status
      ignore_unreachable: yes

    # 2️⃣ Handle Connection Failure (Stop Execution if Unreachable)
    - name: Handle Connection Failure
      block:
        - name: Display Failure Message
          debug:
            msg: >
              "❌ Failed to connect to the Windows server. Possible reasons:
              - Incorrect IP address or unreachable network.
              - WinRM service is not running on the target machine.
              - Authentication failure due to incorrect credentials.
              - Firewall rules blocking WinRM access.
              - The server is down or experiencing issues."
        
        - name: Stop Execution
          meta: end_play
      when: connection_status.unreachable is defined and connection_status.unreachable

    - name: Confirm Connection Success
      debug:
        msg: "✅ Connected successfully to the Windows server. Starting troubleshooting..."
