---
- name: Printer Troubleshooting Automation
  hosts: "{{ target_machine }}"  # Machine IP/Hostname passed as extra variable
  gather_facts: no
  tasks:

    - name: Restart Print Spooler Service
      win_service:
        name: Spooler
        state: restarted
      when: issue_type == "spooler_restart"

    - name: Clear Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object { Remove-PrintJob -PrinterName $_.Name }
      when: issue_type == "stuck_jobs"
      ignore_errors: yes  # Avoids failure if no stuck jobs exist

    - name: Check Printer Connectivity
      win_shell: |
        Test-Connection -ComputerName PRINTER_IP -Count 2
      register: ping_result
      when: issue_type == "connectivity"

    - name: Show Connectivity Result
      debug:
        msg: "{{ ping_result.stdout_lines }}"
      when: issue_type == "connectivity"

    - name: Install Missing Printer Driver
      win_package:
        path: "\\\\fileserver\\drivers\\printer_driver.exe"  # Fixed path syntax
        state: present
      when: issue_type == "driver_update"
      ignore_errors: yes  # Skips if driver is already installed
