---
- name: Printer Troubleshooting Automation
  hosts: all  # Run on all hosts in the inventory
  gather_facts: no
  tasks:

    - name: Restart Print Spooler Service
      win_service:
        name: Spooler
        state: restarted
      when: ansible_host == target_machine and issue_type == "spooler_restart"

    - name: Clear Stuck Print Jobs
      win_shell: |
        Get-Printer | ForEach-Object { Remove-PrintJob -PrinterName $_.Name }
      when: ansible_host == target_machine and issue_type == "stuck_jobs"
      ignore_errors: yes

    - name: Check Printer Connectivity
      win_shell: |
        Test-Connection -ComputerName PRINTER_IP -Count 2
      register: ping_result
      when: ansible_host == target_machine and issue_type == "connectivity"

    - name: Show Connectivity Result
      debug:
        msg: "{{ ping_result.stdout_lines }}"
      when: ansible_host == target_machine and issue_type == "connectivity"

    - name: Install Missing Printer Driver
      win_package:
        path: "\\\\fileserver\\drivers\\printer_driver.exe"
        state: present
      when: ansible_host == target_machine and issue_type == "driver_update"
      ignore_errors: yes
